name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        required: true
        default: '3.13'
      agentifyme_version:
        description: 'AgentifyMe version'
        required: true
        default: '0.2'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/agentifyme-py-runtime

jobs:
  release:
    permissions:
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
      
      - name: Determine versions
        id: versions
        run: |
          # Use input values if provided through workflow_dispatch
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            PYTHON_VERSION="${{ github.event.inputs.python_version }}"
            AGENTIFYME_VERSION="${{ github.event.inputs.agentifyme_version }}"
          else
            # Default values from Dockerfile or repository
            PYTHON_VERSION="3.13"
            AGENTIFYME_VERSION="0.1.0"
          fi
          
          echo "PYTHON_VERSION=${PYTHON_VERSION}" >> $GITHUB_OUTPUT
          echo "AGENTIFYME_VERSION=${AGENTIFYME_VERSION}" >> $GITHUB_OUTPUT
          
          # Set custom tag with versions
          CUSTOM_TAG="${AGENTIFYME_VERSION}-python${PYTHON_VERSION}"
          echo "CUSTOM_TAG=${CUSTOM_TAG}" >> $GITHUB_OUTPUT
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/debian/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PYTHON_VERSION=${{ steps.versions.outputs.PYTHON_VERSION }}
            AGENTIFYME_VERSION=${{ steps.versions.outputs.AGENTIFYME_VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.versions.outputs.CUSTOM_TAG }}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max